version: '3.8'

services:
  audiodeck:
    image: ghcr.io/cb-builds/audiodeck:latest
    container_name: audiodeck-app
    ports:
      - "4000:4000"
    volumes:
      - audiodeck_clips:/app/backend/clips
      - audiodeck_logs:/app/logs
    environment:
      - NODE_ENV=production
      - PORT=4000
      - MAX_FILE_SIZE=26214400
      # Durations are in minutes in the app code
      - MAX_DURATION=20
      - MAX_UPLOAD_DURATION=20
      # Concurrency per canonical site (youtube, tiktok, etc.)
      - MAX_CONCURRENT_DOWNLOADS_PER_SITE=1
      - CLEANUP_INTERVAL=60000 # currently unused; cleanup runs every 1m in code
      - CLIP_TTL_MINUTES=60
      - MAX_STORAGE=524288000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost:4000/api/test', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  audiodeck_clips:
    driver: local
  audiodeck_logs:
    driver: local 