version: '3.8'

services:
  audiodeck:
    image: ghcr.io/cb-builds/audiodeck:latest
    container_name: audiodeck-app
    ports:
      - "${AUDIODECK_PORT:-4000}:4000"
    volumes:
      - audiodeck_clips:/app/backend/clips
      - audiodeck_logs:/app/logs
      - browser_profile:${BROWSER_PROFILE_MOUNT_PATH:-/browser_profile}:ro
    environment:
      - NODE_ENV=production
      - PORT=4000
      - USE_BROWSER_COOKIES=${USE_BROWSER_COOKIES:-true}
      - BROWSER_PROFILE_MOUNT_PATH=${BROWSER_PROFILE_MOUNT_PATH:-/browser_profile}
      - TZ=${TZ:-UTC}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - MAX_FILE_SIZE=26214400
      # Durations are in minutes in the app code
      - MAX_DURATION=20
      - MAX_UPLOAD_DURATION=20
      # Concurrency per canonical site (youtube, tiktok, etc.)
      - MAX_CONCURRENT_DOWNLOADS_PER_SITE=1
      - CLEANUP_INTERVAL=60000 # currently unused; cleanup runs every 1m in code
      - CLIP_TTL_MINUTES=60
      - MAX_STORAGE=524288000
    # audiodeck should always deploy; do not gate behind profiles
  firefox:
    image: lscr.io/linuxserver/firefox:latest
    container_name: audiodeck-firefox
    profiles:
      - firefox
    ports:
      - "${FIREFOX_NOVNC_PORT:-6901}:6901"
    environment:
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}
      - TZ=${TZ:-UTC}
    shm_size: "1g"
    volumes:
      - browser_profile:/config
    restart: unless-stopped

volumes:
  audiodeck_clips:
    driver: local
  audiodeck_logs:
    driver: local 
  browser_profile:
    driver: local